from lxml import html
from time import sleep
from selenium import webdriver


def parse(url):
    response = webdriver.Chrome()
    response.get(url)
    sleep(3)

    ge1keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[1]/article/header')
    print(ge1keyElement.text)
    ge2keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[2]/article/header')
    print(ge2keyElement.text)
    ge3keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[3]/article/header')
    print(ge3keyElement.text)
    ge4keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[4]/article/header')
    print(ge4keyElement.text)
    ge5keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[5]/article/header')
    print(ge5keyElement.text)
    ge6keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[6]/article/header')
    print(ge6keyElement.text)
    ge7keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[7]/article/header')
    print(ge7keyElement.text)
    ge8keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[8]/article/header')
    print(ge8keyElement.text)
    ge9keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[9]/article/header')
    print(ge9keyElement.text)
    ge10keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[10]/article/header')
    print(ge10keyElement.text)
    ge11keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[11]/article/header')
    print(ge11keyElement.text)
    ge12keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[12]/article/header')
    print(ge12keyElement.text)
    ge13keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[13]/article/header')
    print(ge13keyElement.text)
    ge14keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[14]/article/header')
    print(ge14keyElement.text)
    ge15keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[15]/article/header')
    print(ge15keyElement.text)
    ge16keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[16]/article/header')
    print(ge16keyElement.text)
    ge17keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[17]/article/header')
    print(ge17keyElement.text)
    ge18keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[18]/article/header')
    print(ge18keyElement.text)
    ge19keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[19]/article/header')
    print(ge19keyElement.text)
    ge20keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[20]/article/header')
    print(ge20keyElement.text)
    ge21keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[21]/article/header')
    print(ge21keyElement.text)
    sleep(3)
    ge22keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[22]/article/header')
    print(ge22keyElement.text)
    ge23keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[23]/article/header')
    print(ge23keyElement.text)
    ge24keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[24]/article/header')
    print(ge24keyElement.text)
    ge25keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[25]/article/header')
    print(ge25keyElement.text)
    ge26keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[26]/article/header')
    print(ge26keyElement.text)
    ge27keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[27]/article/header')
    print(ge27keyElement.text)
    ge28keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[28]/article/header')
    print(ge28keyElement.text)
    ge29keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[29]/article/header')
    print(ge29keyElement.text)
    ge30keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[30]/article/header')
    print(ge30keyElement.text)
    ge31keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[31]/article/header')
    print(ge31keyElement.text)
    ge32keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[32]/article/header')
    print(ge32keyElement.text)
    ge33keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[33]/article/header')
    print(ge33keyElement.text)
    ge34keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[34]/article/header')
    print(ge34keyElement.text)
    ge35keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[35]/article/header')
    print(ge35keyElement.text)
    ge36keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[36]/article/header')
    print(ge36keyElement.text)
    ge37keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[37]/article/header')
    print(ge37keyElement.text)
    ge38keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[38]/article/header')
    print(ge38keyElement.text)
    ge39keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[39]/article/header')
    print(ge39keyElement.text)
    ge40keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[40]/article/header')
    print(ge40keyElement.text)
    ge41keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[41]/article/header')
    print(ge41keyElement.text)
    ge42keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[42]/article/header')
    print(ge42keyElement.text)
    sleep(3)
    ge43keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[43]/article/header')
    print(ge43keyElement.text)
    ge44keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[44]/article/header')
    print(ge44keyElement.text)
    ge45keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[45]/article/header')
    print(ge45keyElement.text)
    ge46keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[46]/article/header')
    print(ge46keyElement.text)
    ge47keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[47]/article/header')
    print(ge47keyElement.text)
    ge48keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[48]/article/header')
    print(ge48keyElement.text)
    ge49keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[49]/article/header')
    print(ge49keyElement.text)
    ge50keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[50]/article/header')
    print(ge50keyElement.text)
    ge51keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[51]/article/header')
    print(ge51keyElement.text)
    ge52keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[52]/article/header')
    print(ge52keyElement.text)
    ge53keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[53]/article/header')
    print(ge53keyElement.text)
    ge54keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[54]/article/header')
    print(ge54keyElement.text)
    ge55keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[55]/article/header')
    print(ge55keyElement.text)
    ge56keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[56]/article/header')
    print(ge56keyElement.text)
    ge57keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[57]/article/header')
    print(ge57keyElement.text)
    ge58keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[58]/article/header')
    print(ge58keyElement.text)
    ge59keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[59]/article/header')
    print(ge59keyElement.text)
    ge60keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[60]/article/header')
    print(ge60keyElement.text)
    ge61keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[61]/article/header')
    print(ge61keyElement.text)
    ge62keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[62]/article/header')
    print(ge62keyElement.text)
    ge63keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[63]/article/header')
    print(ge63keyElement.text)
    sleep(3)
    ge64keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[64]/article/header')
    print(ge64keyElement.text)
    ge65keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[65]/article/header')
    print(ge65keyElement.text)
    ge66keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[66]/article/header')
    print(ge66keyElement.text)
    ge67keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[67]/article/header')
    print(ge67keyElement.text)
    ge68keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[68]/article/header')
    print(ge68keyElement.text)
    ge69keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[69]/article/header')
    print(ge69keyElement.text)
    ge70keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[70]/article/header')
    print(ge70keyElement.text)
    ge71keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[71]/article/header')
    print(ge71keyElement.text)
    ge72keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[72]/article/header')
    print(ge72keyElement.text)
    ge73keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[73]/article/header')
    print(ge73keyElement.text)
    ge74keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[74]/article/header')
    print(ge74keyElement.text)
    ge75keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[75]/article/header')
    print(ge75keyElement.text)
    ge76keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[76]/article/header')
    print(ge76keyElement.text)
    ge77keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[77]/article/header')
    print(ge77keyElement.text)
    ge78keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[78]/article/header')
    print(ge78keyElement.text)
    ge79keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[79]/article/header')
    print(ge79keyElement.text)
    ge80keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[80]/article/header')
    print(ge80keyElement.text)
    ge81keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[81]/article/header')
    print(ge81keyElement.text)
    ge82keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[82]/article/header')
    print(ge82keyElement.text)
    ge83keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[83]/article/header')
    print(ge83keyElement.text)
    ge84keyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[84]/article/header')
    print(ge84keyElement.text)
    ge1akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[85]/article/header')
    print(ge1akeyElement.text)
    ge2akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[86]/article/header')
    print(ge2akeyElement.text)
    ge3akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[87]/article/header')
    print(ge3akeyElement.text)
    ge4akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[88]/article/header')
    print(ge4akeyElement.text)
    ge5akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[89]/article/header')
    print(ge5akeyElement.text)
    ge6akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[90]/article/header')
    print(ge6keyElement.text)
    ge7akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[91]/article/header')
    print(ge7akeyElement.text)
    ge8akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[92]/article/header')
    print(ge8akeyElement.text)
    ge9akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[93]/article/header')
    print(ge9akeyElement.text)
    ge10akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[94]/article/header')
    print(ge10akeyElement.text)
    ge11akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[95]/article/header')
    print(ge11akeyElement.text)
    ge12akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[96]/article/header')
    print(ge12akeyElement.text)
    ge13akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[97]/article/header')
    print(ge13akeyElement.text)
    ge14akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[98]/article/header')
    print(ge14akeyElement.text)
    ge15akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[99]/article/header')
    print(ge15akeyElement.text)
    ge16akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[100]/article/header')
    print(ge16akeyElement.text)
    ge17akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[101]/article/header')
    print(ge17akeyElement.text)
    ge18akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[102]/article/header')
    print(ge18akeyElement.text)
    ge19akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[103]/article/header')
    print(ge19akeyElement.text)
    ge20akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[104]/article/header')
    print(ge20akeyElement.text)
    ge21akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[105]/article/header')
    print(ge21akeyElement.text)
    ge22akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[106]/article/header')
    print(ge22akeyElement.text)
    ge23akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[107]/article/header')
    print(ge23akeyElement.text)
    ge24akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[108]/article/header')
    print(ge24akeyElement.text)
    ge25akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[109]/article/header')
    print(ge25akeyElement.text)
    ge26akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[110]/article/header')
    print(ge26akeyElement.text)
    ge27akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[111]/article/header')
    print(ge27akeyElement.text)
    ge28akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[112]/article/header')
    print(ge28akeyElement.text)
    ge29akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[113]/article/header')
    print(ge29akeyElement.text)
    ge30akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[114]/article/header')
    print(ge30akeyElement.text)
    ge31akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[115]/article/header')
    print(ge31akeyElement.text)
    ge32akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[116]/article/header')
    print(ge32akeyElement.text)
    ge33akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[117]/article/header')
    print(ge33akeyElement.text)
    ge34akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[118]/article/header')
    print(ge34akeyElement.text)
    ge35akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[119]/article/header')
    print(ge35akeyElement.text)
    ge36akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[120]/article/header')
    print(ge36akeyElement.text)
    ge37akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[121]/article/header')
    print(ge37akeyElement.text)
    ge38akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[122]/article/header')
    print(ge38akeyElement.text)
    ge39akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[123]/article/header')
    print(ge39akeyElement.text)
    ge40akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[124]/article/header')
    print(ge40akeyElement.text)
    ge41akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[125]/article/header')
    print(ge41akeyElement.text)
    ge42akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[126]/article/header')
    print(ge42akeyElement.text)
    ge43akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[127]/article/header')
    print(ge43akeyElement.text)
    ge44akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[128]/article/header')
    print(ge44akeyElement.text)
    #ge45akeyElement = response.find_element_by_xpath('//*[@id="ng-app"]/div[5]/div/div/div/div/div[2]/div[129]/article/header')
    #print(ge45akeyElement.text)

    sleep(4)


if __name__ == '__main__':

    parse('http://www.scandpipes.com/pipes/26-pipe-makers/')
